-- Historial de inicios de sesion para el dashboard.
-- Los eventos se registran despues de un signIn exitoso; no se exponen
-- directamente y solo los responsables de catalogos consultan agregados.

CREATE TABLE IF NOT EXISTS public.user_login_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  logged_in_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_login_events_logged_in_at_idx
  ON public.user_login_events (logged_in_at);

CREATE INDEX IF NOT EXISTS user_login_events_user_id_logged_in_at_idx
  ON public.user_login_events (user_id, logged_in_at DESC);

ALTER TABLE public.user_login_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.user_login_events FROM anon, authenticated;

-- Supabase solo conserva el ultimo acceso. Se usa como punto inicial para que
-- la grafica no nazca vacia; los accesos siguientes ya forman historial real.
INSERT INTO public.user_login_events (user_id, logged_in_at)
SELECT au.id, au.last_sign_in_at
FROM auth.users au
WHERE au.last_sign_in_at IS NOT NULL
  AND NOT EXISTS (
    SELECT 1
    FROM public.user_login_events e
    WHERE e.user_id = au.id
      AND e.logged_in_at = au.last_sign_in_at
  );

CREATE OR REPLACE FUNCTION public.record_user_login_event()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
VOLATILE
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'No autorizado'
      USING ERRCODE = '42501';
  END IF;

  INSERT INTO public.user_login_events (user_id)
  VALUES (auth.uid());
END;
$$;

COMMENT ON FUNCTION public.record_user_login_event() IS
  'Registra un inicio de sesion para el usuario autenticado.';

REVOKE ALL ON FUNCTION public.record_user_login_event() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.record_user_login_event() TO authenticated;

DROP FUNCTION IF EXISTS public.dashboard_user_login_buckets(text);

CREATE OR REPLACE FUNCTION public.dashboard_user_login_buckets(
  p_granularity text DEFAULT 'weekly'
)
RETURNS TABLE (
  bucket_start date,
  bucket_end date,
  users_logged_in integer,
  users_total integer
)
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
DECLARE
  v_today date := (now() AT TIME ZONE 'America/Mexico_City')::date;
  v_granularity text := lower(trim(coalesce(p_granularity, 'weekly')));
BEGIN
  IF auth.uid() IS NULL OR NOT public.can_manage_catalogs() THEN
    RAISE EXCEPTION 'No autorizado'
      USING ERRCODE = '42501';
  END IF;

  IF v_granularity NOT IN ('weekly', 'biweekly', 'monthly') THEN
    RAISE EXCEPTION 'Granularidad invalida'
      USING ERRCODE = '22023';
  END IF;

  RETURN QUERY
  WITH candidate_periods AS (
    SELECT
      gs::date AS period_start,
      (gs + interval '6 days')::date AS period_end
    FROM generate_series(
      date_trunc('week', v_today::timestamp) - interval '7 weeks',
      date_trunc('week', v_today::timestamp),
      interval '1 week'
    ) gs
    WHERE v_granularity = 'weekly'

    UNION ALL

    SELECT
      month_start::date AS period_start,
      (month_start + interval '14 days')::date AS period_end
    FROM generate_series(
      date_trunc('month', v_today::timestamp) - interval '4 months',
      date_trunc('month', v_today::timestamp),
      interval '1 month'
    ) month_start
    WHERE v_granularity = 'biweekly'

    UNION ALL

    SELECT
      (month_start + interval '15 days')::date AS period_start,
      (month_start + interval '1 month - 1 day')::date AS period_end
    FROM generate_series(
      date_trunc('month', v_today::timestamp) - interval '4 months',
      date_trunc('month', v_today::timestamp),
      interval '1 month'
    ) month_start
    WHERE v_granularity = 'biweekly'

    UNION ALL

    SELECT
      month_start::date AS period_start,
      (month_start + interval '1 month - 1 day')::date AS period_end
    FROM generate_series(
      date_trunc('month', v_today::timestamp) - interval '7 months',
      date_trunc('month', v_today::timestamp),
      interval '1 month'
    ) month_start
    WHERE v_granularity = 'monthly'
  ),
  periods AS (
    SELECT cp.period_start, cp.period_end
    FROM candidate_periods cp
    WHERE cp.period_start <= v_today
    ORDER BY cp.period_start DESC
    LIMIT 8
  ),
  active_users AS (
    SELECT DISTINCT u.user_id
    FROM public.usuarios u
    WHERE u.activo = true
      AND u.user_id IS NOT NULL
  ),
  active_total AS (
    SELECT count(*)::integer AS total
    FROM active_users
  )
  SELECT
    p.period_start,
    p.period_end,
    count(DISTINCT e.user_id)::integer AS users_logged_in,
    t.total AS users_total
  FROM periods p
  CROSS JOIN active_total t
  LEFT JOIN public.user_login_events e
    ON (e.logged_in_at AT TIME ZONE 'America/Mexico_City')::date
      BETWEEN p.period_start AND LEAST(p.period_end, v_today)
    AND EXISTS (
      SELECT 1
      FROM active_users au
      WHERE au.user_id = e.user_id
    )
  GROUP BY p.period_start, p.period_end, t.total
  ORDER BY p.period_start;
END;
$$;

COMMENT ON FUNCTION public.dashboard_user_login_buckets(text) IS
  'Inicios de sesion unicos de usuarios activos en los ultimos ocho periodos.';

REVOKE ALL ON FUNCTION public.dashboard_user_login_buckets(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.dashboard_user_login_buckets(text) TO authenticated;
